image: continuumio/miniconda3:latest

before_script:
  - conda create -y -n nextflow -c conda-forge -c bioconda nextflow
  - conda activate nextflow 

test:
  script:
    - nextflow run main.nf -profile example,ci

