image: ubuntu:18.04

before_script:
 - apt-get update
 - yes | apt-get install wget procps
 - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - source "$HOME/miniconda/etc/profile.d/conda.sh"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 # Useful for debugging any issues with conda
 - conda info -a
 - conda create -q -c bioconda -c conda-forge -n nextflow nextflow
 - conda activate nextflow

test:
  script:
    - nextflow run main.nf -profile example,ci

