image: continuumio/miniconda3:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - apt-get update && apt-get -y install build-essential make
  - conda info -a
  - |
    conda install -c conda-forge \
      flit \
      python-igraph \
      pandoc \
      python-igraph \
      leidenalg \
      python-levenshtein
  - FLIT_ROOT_INSTALL=1 flit install --deps all

test:
  script:
    - CWD=$(pwd)
    - black --check scirpy
    - pytest

docs:
  script:
    - cd docs && make html
