image: continuumio/miniconda3:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - conda info -a
  - conda install -y flit pandoc
  - FLIT_ROOT_INSTALL=1 flit install --deps develop

test:
  script:
    - CWD=$(pwd)
    - black --check sctcrpy
    - pytest

docs:
  script:
    - cd docs && make html
