image: python:3.8

before_script:
  - pip install flit
  - FLIT_ROOT_INSTALL=1 flit install --deps develop

test:
  script:
    - CWD=$(pwd)
    - black --check sctcrpy
    - pytest
    - cd docs && make html
    - cd $CWD/tutorial && python demo.py
