language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install flit
  - flit install --deps develop

script:
  - black --check sctcrpy
  - pytest

after_success:
  - mkdir -p deploy_docs && cd docs && make html && mv _build/html ../deploy_docs/5vLj3lcBVp2VkVEpIt3j

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: deploy_docs 
  on:
    branch: package 
